[package]
name = "airev-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { workspace = true }
tokio-rusqlite = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3.25.0"
